# Generated by Django 3.2.7 on 2021-09-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=11, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('status', models.BooleanField(default=False)),
                ('job_description', models.CharField(max_length=200, null=True)),
                ('skills', models.CharField(max_length=200, null=True)),
                ('date_graduated', models.DateField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, default='default_profile.png', null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
