# Generated by Django 3.2.7 on 2021-09-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.BooleanField(blank=True, choices=[('Employed', 'Employed'), ('Unemployed', 'Unemployed')], max_length=100, null=True),
        ),
    ]
